# Justice Equity Diversity and Inclusion Policy {-#diversity}

The Conservation Decisions Lab and the Arcese Lab at the University of British Columbia---led by Dr. Tara Martin and Dr. Peter Arcese, respectively---have worked together to develop this [Justice, Equity, Diversity, and Inclusion (JEDI) policy](https://www.taramartin.org/equity-diversity-and-inclusion/). Each year, we come together to review the policy and make changes in response to changing needs, social and cultural contexts, and understanding of JEDI principles and how they apply to our work and our daily lives. Throughout the year, lab members also engage in  discussions and share information about available learning opportunities, such as articles, seminars, workshops, or resources, to deepen our understanding of these principles and how to embody them in our actions.

## Our Statement {-#statement}

We recognize the colonial contexts of conservation and academia, both past and present, and the systemic inequities that prevail. We see it as our responsibility to encourage, include, and make way for underrepresented and marginalized voices and perspectives; meaningfully collaborate with and support the work of Indigenous communities; and communicate our research to a broad cross-section of society across all demographics. 

We commit to decolonizing the work that we do, from the questions that we pose to the manner in which we undertake our research and communicate the outcomes. We commit to using our privilege to actively address any barriers or injustices witnessed in our work and daily life. We commit to working in a self-reflective and critical manner, and adapting and improving our actions to ensure our impacts align with the values of Justice, Equity, Diversity, and Inclusion.

Our labs are committed to recruiting and collaborating with people of diverse backgrounds, identities, experiences, and perspectives. We believe that diversity is critical for transforming us into better students, teachers, scientists, conservation practitioners, and members of all communities. The challenges we face in conservation and as a society at large—whether they be related to biodiversity, climate change, and/or JEDI—require a shared understanding, novel perspectives, and transformative actions. We are actively working to reduce barriers to diverse representation in our research, in conservation, and in academia. Through this process, we aim to share knowledge, experience, and insight with each other that can be applied to our future workplaces, many of which share similar legacies of systemic inequality. 

We acknowledge that our labs---centered at UBC Vancouver---are located on the traditional, ancestral, and unceded territory of the Coast Salish Peoples.[The land where UBC is situated has always been a place of learning where people for millennia have passed on their culture, history, and traditions from one generation to the next.](https://indigenous.ubc.ca/indigenous-engagement/musqueam-and-ubc/) Members of our lab engage in research on this land, as well as in the territories of other First Nations in BC and Indigenous communities across Canada. We have a duty to reflect on the nature of our work and reconcile it with the history and ongoing nature of colonialism, academic research, and Indigenous dispossession. It is our intent to foster meaningful relationships with the communities whose lands we are working on and engage in a research process that is beneficial to and is anchored by the values, goals, and interests of those communities and is conducted in the spirit of reciprocity.

We acknowledge that each of us may be at different points throughout our journey in learning, listening, and cultivating an inclusive academic environment and that mistakes can be made. We also understand how important it is to learn from those mistakes and to not let fear of making a mistake be an excuse for inaction. To guide our journey, we are committed to continuously revisiting these values and updating this JEDI statement as a living document. 

## Our Values {-#values}

We value diversity of identities, knowledge systems, and worldviews in our lab and community. 

We value a lab culture whereby we can reflect on our personal and collective identities, both as researchers and as colleagues. This means we are actively acknowledging the intersecting privilege and/or barriers that we may or may not experience associated with our identities.

We value acceptance. Discrimination—e.g., unjust treatment on the basis of sex, race, gender identity, sexual orientation, religion, socioeconomic background, national origin, education level, physical and mental ability, age, physical appearance, or political views—in any form will not be tolerated within this space. Derogatory or hurtful comments are not acceptable, and all lab members are encouraged to initiate discussion when inappropriate behaviour or language is observed. 

We value accountability in supporting and nurturing a culture of safety within our team. All members of our team commit to creating a safe, supportive, respectful, and inviting community. 

We value an ongoing and iterative journey of learning. We recognize the continuous commitment to (un)learning needed to build a more just, equitable, diverse, and inclusive community. 

We commit to translating these values into action and carrying them out in our work and daily life. 

## Our Commitment to Action {-#jediactions}

### Individual Actions {-#individualactions}

* Recognize and reflect on one's own bias and privilege. Recognize privilege (e.g., status or experience) as a responsibility to provide space for underrepresented or overlooked contributors before ourselves. 
* Devote time to continue learning about JEDI issues, working through provided JEDI materials, sourcing new materials, and contributing to the lab’s [EDI materials library.](https://docs.google.com/document/d/102fsqZL8UVf22TX1kTZ1WjQu2U9SrFjEBbQ9NipedXA/edit#heading=h.axugsem4agey)
* Practice deep listening to ensure we are working with peers and collaborators in a meaningful way, rather than dictating or projecting our needs onto others.
* Welcome critiques of our words and actions, and remain open to engaging in uncomfortable conversations that are integral to change. Complete UBC’s conflict engagement course [here.](https://wpl.ubc.ca/browse/conflict-theatre/courses/wpl-pd-icsd)
* Invite speakers, panels, authorship, and committees to better represent the diversity of perspectives and lived experiences.
* Include local knowledge holders, practitioners, and scientists from other disciplines in our research during study design, questions, analyses, and writing.
* Communicate and provide research outputs to those involved in and affected by the research and possible decisions influenced by this research. 
* Commit to open science and data sharing when appropriate (e.g., with permission for any data that might be sensitive).
* Maintain epistemic humility and scrutinize methods, concepts, and questions using a multi-dimensional lens.
* Use inclusive pronouns and language.
* Be willing to share ideas, projects, and concepts with others.
* Recognize the Nations whose lands we conduct our research on, and include them meaningfully in all steps of our research process.

### Lab Community Actions {-#labactions}

* Use this document as a social contract to foster a safe space within our lab community.
* Actively update this document to reflect new perspectives and growth annually during lab events. 
*Devote time to discussing JEDI materials, including JEDI-focused activities and group exercises, during lab events.
* Provide resources for members to attend JEDI courses, training, and workshops. 
* Continuously build and update the online and physical JEDI learning library in the lab. 
*Invite speakers, panels, authorship, and committees to better represent a diversity of perspectives and lived experiences.
* Facilitate discussion aimed to educate and encourage lab members on the best practices of including local knowledge holders, community groups, practitioners, and scientists from other disciplines in our research.
* Ensure that lab events are inclusive, accessible and safe for all lab members by providing multiple event options for venues and activities.
* Discuss one’s own and other’s research in the context of our JEDI values to ensure our research aligns with the values and best practices outlined in this document.

## Best Practices in Research {-#researchpractices}

We are committed to building our fluency and capacity in the following areas to facilitate best practices in JEDI in our research:

* Acknowledging power and vulnerabilities
  *	Follow best practices in JEDI in hiring and retainment, and encourage the department to follow suite
  *	Encourage reflexivity and positionality statements in grad student/postdoc applications
  * Provide basic JEDI training when involved in a hiring process 
  *	Participate in basic JEDI training when involved in a hiring process
  * Confronting harassment in the workplace 

*	Committing to transparency and accountability to the implications of our works
    *	E.g., Who benefits, who is impacted? 
    *	Titleholder and stakeholder engagement throughout the research process
    *	Clarity around ownership and control of data
    *	Fairly acknowledging contributions
    *	Encourage reflexivity and positionality statements in your work and research

*	Committing to accessibility
    *	E.g., Communicating our research to diverse audiences 
    *	Open access data (where appropriate), code, and publications
    *	Examining reward systems within and beyond academia (e.g., what constitutes “good” research questions, reward systems for research participants)
    *	Equitable hiring relative to opportunities (e.g., consider paid positions vs volunteers, make space early and often for conversations around additional resources and capacity for hiring graduate students and PDFs)

*	Decolonizing our approach to research
    *	E.g., Fostering collaborative approaches to co-developing research, practicing accountability (e.g., “helicopter research”), and being open to timeframes and reward systems outside of academia
    *	Access training for appropriate ethics (e.g., UBC and Nation/community-specific intake processes), communication, and decolonizing 
    *	“Doing our homework” - knowing where we work and the historical context of the systems we get to work in
    *	Be open and curious to multiple ways of knowing, learning, and communicating

*	Daylighting health and wellness
    *	Prioritizing our own and each other’s mental health in grad school
    *	Openly discussing / holding space for health and wellness obstacles, personally and professionally (i.e., in academic spaces) 
    *	Celebrating success beyond the h-index and the awards list! 

## Resources {-#jediresources}

As a part of our JEDI commitment we have established an [online resources center](https://docs.google.com/document/d/102fsqZL8UVf22TX1kTZ1WjQu2U9SrFjEBbQ9NipedXA/edit#heading=h.axugsem4agey) for JEDI related materials. This is by no means a complete or exhaustive list. We encourage all lab members to add to this resource pool. Thank you in advance for contributing material that you believe will assist in our collective education. 



