# Moving to BC {#newvancouver .unnumbered}

This is by no means an exhaustive list of tips and tricks for those who are new to the great city of Vancouver. Many of our lab members are from elsewhere in Canada and the world and have gone through the process of moving and settling in Vancouver, and will be happy to give tips. We urge for you to communicate via our [slack](#slack), [email](#contacts), or in person with other lab members who live in Vancouver and who will be able to provide more information and suggestions on how to enjoy the city to its fullest extent.

If you are moving to BC from outside of Canada, you may need to obtain a student or work visa prior to arrival. It is best to apply as soon as you have been accepted to allow for lengthy processing times. See the [Canadian Immigration and Citizenship website](https://www.canada.ca/en/services/immigration-citizenship.html) for information about VISA applications and renewals, working while studying, and staying in Canada post-graduation. See also UBC Student Services [Immigration Guide for International Students](https://students.ubc.ca/international-student-guide/immigration). Pedro Ribeiro (<pedro.ribeiro@ubc.ca>) may also be able to help get you in touch with a UBC immigration lawyer. 

Information and other helpful resources on moving to and settling in BC are available from the BC Government website, for those moving from [outside](https://www.welcomebc.ca/start-your-life-in-b-c) Canada and from another province [within](https://www2.gov.bc.ca/gov/content/tourism-immigration/moving-bc-a) Canada. Some information about relocating to BC are also available from the [UBC HR website](https://hr.ubc.ca/working-ubc/housing-immigration-and-relocation-services/relocating-vancouver).

## Housing {#housing .unnumbered}

It is worth knowing that in BC, lease periods begin on the 1st of the month and sometimes on the 15th. The term of lease agreement varies from month to month, three months, 6 months, and a year. Note that many landlords will ask for references and/or proof of income as part of the rental application.

For those who are new to renting, the [Housing and Tenancy page](https://www2.gov.bc.ca/gov/content/housing-tenancy) on the BC government website provides great resources on how to ensure that you legally protect yourselves as a tenant. It is highly recommended to ensure that your landlord provides you with a [lease agreement](https://www2.gov.bc.ca/gov/content/housing-tenancy/residential-tenancies/starting-a-tenancy/tenancy-agreements), regardless of history or personal connections.

Feel free to use the [CDL Slack](#slack) group to ask other lab members about the process of housing in Vancouver.

Here are some resources for finding housing in Vancouver:

* For information about on-campus residences at UBC Vancouver, see the UBC Student Housing [website](https://vancouver.housing.ubc.ca/)
* Other resources include *Facebook Marketplace*, *Craigslist*, and *Used Vancouver*
* There are also Facebook groups that advertise rentals, sublets and housemates, including *Vancouver Rentals and Roommates*, *For Rent Vancouver*, *Vancouver Apartments/Houses for Rent/Roommates*, *Vancouver Buy/Sell Fast*, and *Aussies in Vancouver*
* Some have also had success by walking the neighborhoods they are interested in looking for vacancy signs out the front of buildings

## Finances {#finance .unnumbered}

For opening bank accounts in BC, [here](https://www.canada.ca/en/financial-consumer-agency/services/banking/opening-bank-account.html) are some helpful tips. Make sure you bring sufficient ID if opening an account in person! There are many options for banks---including Scotiabank, BMO, CIBC, TD Bank, RBC, Vancity, and more.

For information on filing taxes in BC & Canada, check out the UBC [Tax Filing](https://students.ubc.ca/enrolment/finances/taxes/filing-taxes-canada) information page as well as the [BC CRA](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/individuals-leaving-entering-canada-non-residents/international-students-studying-canada.html) information pages. Important steps and considerations include:

- Apply for [Social Insurance Number (SIN)](https://students.ubc.ca/enrolment/finances/taxes/social-insurance-number-sin), in which you must have a work permit or a study permit which includes a condition to work on and/or off campus. If you are not eligible for a SIN, apply for an [Individual Tax Number (ITN)](https://students.ubc.ca/enrolment/finances/taxes/individual-tax-number-itn), necessary for student scholarship. 
- Likely tax documents for students in Canada/BC are T2202, T4, T4A, which you can download from [Workday](https://workday.students.ubc.ca/finances/downloading-your-tax-forms/). 
- The Canadian tax system is based on your [residency status](https://www.canada.ca/en/revenue-agency/services/tax/international-non-residents/individuals-leaving-entering-canada-non-residents/international-students-studying-canada.html), not citizenship. You can file online, by paper, by mail, or with accounts, with more information on if you need to file and how to file [here](https://students.ubc.ca/enrolment/finances/taxes/filing-taxes-canada). 
- For support you can access the UBC [Tax Assistance Clinic (UBC TACS)](https://www.ubctacs.com/), [CRA Free tax clinics](https://www.canada.ca/en/revenue-agency/campaigns/free-tax-help.html), or other resources. 
- Note that you may have to file taxes both in Canada and your country of citizenship. Depending on the country, there are some [tax agreements]() in place to prevent double-taxation. This may require filing additional forms when filing taxes for one or both countries.

## Provincial Services {#provincialservices .unnumbered}

Depending on your residency status, you may need to apply for a [BC Services Card](https://www2.gov.bc.ca/gov/content/governments/government-id/bc-services-card/your-card/get-a-card) upon arrival to access provincial services, including health care.

For information on health insurance in BC, check out the [UBC Health Insurance page](https://students.ubc.ca/health/health-insurance). Important steps include: 

- Apply for BC’s [Medical Services Plan (MSP)](https://www2.gov.bc.ca/gov/content/health/health-drug-coverage/msp) upon arrival in BC 
- There is a three month waiting period for MSP coverage to start, so have private medical insurance if you are an international student ([iMED](https://students.ubc.ca/health/health-insurance/health-insurance-international)). For Canadian students moving from outside BC, you should be covered by your former provincial health care plan during the waiting period. 
- For students, you will be automatically enrolled in [AMS/GSS Health and Dental Plan](https://www.ams.ubc.ca/support-services/health-dental/), and at the start of the academic year as you are automatically charged the [AMS/GSS Health and Dental fee](https://www.studentcare.ca/rte/en/UniversityofBritishColumbiaAMSGSS_Cost_HowMuchDoesItCost) 
- For postdocs/staff: depending on your appointment, you may be eligible for Extended Health and Dental Benefits. Enrollment will be done as part of your staff onboarding process.

## Driving {-#driving}

For driving in BC, there are a couple of options, including the following to consider: 

- Upon arrival in BC, you have 90 days to switch your existing license over to a BC one, if needed. NOTE that full-time students may be exempt from this rule. Consult the [ICBC website](https://www.google.com/url?q=https://www.icbc.com/driver-licensing/moving-bc&sa=D&source=docs&ust=1730921193179260&usg=AOvVaw1qKw2PJkMngUwd0rNTK7LN) for more information about the process, including eligibility and required documentation. If you are moving from outside Canada, it is best to prepare the required documentation prior to your arrival. 

- Car registration and insurance is a fairly straightforward process with most information on the ICBC site about [registration](https://www.icbc.com/insurance/moving-travelling/moving-BC) and [insurance](https://www.icbc.com/insurance/moving-travelling/insurance-discount-for-new-residents), but consider the following: 
  - You have 30 days to register, license, and insure your vehicle after arriving in BC 
  - Book an appointment (or show up) with your nearest [autoplan broker](https://www.icbc.com/locators/autoplan-broker?type=2&subtype=0) (provide ICBC services) for registering and insuring your car. There is one in Wesbrook Village that is very close to UBC. 
  - Make sure you have proof of driving experience (abstract or license) already sent directly to ICBC for drivers license as well as bring additional identification. Note that it is significantly cheaper to have insurance in BC if you have a long driving record (sent to ICBC) and if you already get a BC license before registering your car and getting insurance. 
  - Importing a car to BC is difficult and involves many steps but is possible with perseverance. There is extensive information provided [here](https://www.icbc.com/vehicle-registration/buy-vehicle/Importing-a-vehicle-into-B-C) about the steps and the forms needed. You will need to import it officially across the border and get it inspected before registration. 
  - Note that if you are a U.S. citizen bringing your car to the province and are enrolled full-time at a recognized B.C educational institution, you won't need to register your vehicle. Just apply for a non-resident exemption permit within 30 days of your arrival so that you can drive here. This permit allows you to continue using the registration, license and insurance coverage from your home state, for as long as you're studying here. However, not many insurance companies are willing to insure cars in Canada, so you will need to hunt for one, although your car will be insured in Canada for up to 6 months of recreational travel if you are bringing short-term.

- If you have a valid driving license but do not own (nor wish to own) a vehicle, you may be able to sign up for car sharing services, such as [Evo](https://evo.ca/) or [Modo](https://www.modo.coop/).

## Events {#vancouverevents .unnumbered}

There are many [festivals and events throughout the year in Vancouver](https://www.destinationvancouver.com/events/calendar-of-events/). Some that are recommended by lab members are: 

* Cherry Blossom Festival (April)
* Celebration of Light (July)
* Vancouver Folk Music Festival (July)
* Pride (BC Day weekend, August)
* Vancouver International Film Festival [VIFF] (September)
* Fringe Festival (September)
* Westward Music festival (September)
* Vancouver Christmas Market (November-December)

## Statutory Holidays {#statutory .unnumbered}

Statutory holidays recognized as paid holidays by UBC can be found listed [here](https://hr.ubc.ca/working-ubc/statutory-holidays).
