# New to Vancouver {-#newvancouver}

This is by no means an exhaustive list of tips and tricks for those who are new to the great city of Vancouver. Many of our lab members are from elsewhere in Canada and the world and so have gone through the process of moving and settling in Vancouver, and will be happy to give tips. We urge for you to communicate via our [slack](#slack), via email or in person with other lab members who live in Vancouver and who will be able to provide more information and suggestions on how to enjoy the city to it’s fullest extent. 

## Cultural Awareness {-#vancouverculture}

As stated in our lab’s EDI statement Dr. Tara Martin encourages and supports lab members to take time to become aware of the culture surrounding Vancouver and the areas where research is conducted and beyond. 

It is expected that each lab member begins to familiarize themselves with the lush cultural surroundings of Vancouver and the Point Grey Campus. You will notice that a land acknowledgment is common practice during introductions. UBC provides [a guide](https://guides.library.ubc.ca/distance-research-xwi7xwa/landacknowledgements) to assist those new to the land acknowledgment practice and we encourage all lab members to participate in this brief yet vital ‘Respect, Sincerity & Responsibility: Land Acknowledgements @ UBC’ course. Enroll [here](https://wpl.ubc.ca/browse/orientation-and-onboarding/courses/wpl-oo-ilpla).

For those incoming lab members that are new to Canada and Canadians alike, we highly recommend and encourage enrolling in the ‘[Indigenous Canada](https://www.coursera.org/learn/indigenous-canada)’ course offered by the University of Alberta and hosted by coursera which provides effective context to Canada’s history of colonization. This is a great course and is expected to take 21 hours to complete. 

We also greatly encourage new lab members to familiarize themselves with the [First Nations House of Learning](https://indigenous.ubc.ca/longhouse/fnhl/) at UBC which is an incredible resource and provides opportunity to learn about how you can actively work to decolonize your own world view. 

## Events {-#vancouverevents}

There are many [festivals and events throughout the year in Vancouver](https://www.destinationvancouver.com/events/calendar-of-events/). Some that are recommended by lab members are:
* Cherry Blossom Festival (April)
* Celebration of Light (July)
* Vancouver Folk Music Festival (July)
* Pride (BC Day weekend, August)
* Vancouver International Film Festival (September)
* Fringe Festival (September)
* Westward Music festival (September)
* Vancouver Christmas Market (November-December)

## Statutory Holidays {-$statutory}

Statutory holidays recognized as paid holidays by UBC can be found listed [here](https://hr.ubc.ca/working-ubc/statutory-holidays).

## Housing {-#housing}

There are 14 on-campus residences at UBC Vancouver. Visit [https://vancouver.housing.ubc.ca/](https://vancouver.housing.ubc.ca/) to find out more.

If you are planning a move to Vancouver some of the most effective resources are Facebook, Craigslist, and Used Vancouver. Some have also had success by walking the neighborhoods they are interested in looking for vacancy signs out the front of buildings. 

There are many Facebook groups that advertise rentals, sublets and housemates, including Vancouver Rentals and Roommates, For Rent Vancouver, Vancouver apartments/houses for rent/roommates, Vancouver Buy/Sell Fast and Aussies in Vancouver. We encourage the use of our [Slack](#slack) where new members may ask housing related questions of those how have also gone through the process of finding housing in Vancouver. 

It is worth knowing that in BC, lease periods begin on the 1st of the month and sometimes on the 15th. The term of lease agreement varies from month to month, three months, 6 months, and a year.

For those who are new to renting the [Housing and tenancy page of the BC government website](https://www2.gov.bc.ca/gov/content/housing-tenancy) provides great resources on how to ensure that you legally protect yourselves as a tenant. It is highly recommended to ensure that your landlord provides you with a [lease agreement](https://www2.gov.bc.ca/gov/content/housing-tenancy/residential-tenancies/starting-a-tenancy/tenancy-agreements) regardless of history or personal connections. 