# Staffing Roles {-#staffroles}

**Dr. Abbey Camaclang (PhD) – Research Associate**
I lead a number of projects focusing on applications of decision science tools and frameworks to conservation problems. In particular, I often work in collaboration with other scientists, NGOs, government agencies, or industry partners to apply the Priority Threat Management approach in various regions across Canada and elsewhere. Happy to chat about decision science, expert elicitation, or workshop organization/facilitation, and to provide feedback on presentations and draft manuscripts.  
Contact: <abbey.camaclang@ubc.ca>

**Riley Finn (MSc) – [Senior] Research Technician**
I work on several projects in the lab, both independently and in a supporting role. I have a particular interest in, and experience with cartography in QGIS and spatial analysis with R. Much of my work is related to mapping cumulative effects and decision science tools like spatial optimization using a wide range of publicly-available datasets. If you have questions related to programming or mapping, accessing public data sets, or spatial aspects of decision science I am always happy to chat!  
Contact: <riley.finn@ubc.ca>

**Aidan Haigh (BA Geography) – Research Technician and Field Coordinator**
I work on research Tara is interested in pursuing in the Salish Sea, working a lot with non-invasive animal monitoring methods (*e.g.*, camera traps, ARUs), and support student projects when they require an extra set of hands. I have helped students with field work, archival & spatial data collection, and spatial analysis. I am happy to support any aspect of students’ work as long as they clear how much of my time they require with Tara. I also oversee use and maintenance of field equipment, including the research boat & vehicle, so come chat to me if you need to coordinate field work in the Salish Sea, require access to any of the field gear, or are curious about what field gear is available to use.  
Contact: <aidanhaigh@gmail.com>

**Madeline Woodley (BSc) – Research Technician and Lab Manager**
In my role as a research tech, I work largely on research in the Salish Sea. This includes supporting student projects, as well as managing independent projects for Tara and through contracts with non-profits. Generally, I support projects heavy on vegetation sampling and have recently worked on a couple of projects involving qualitative analysis, but have experience working with a variety of datatypes, including archival and spatial data. I am happy to offer project support for students, so long as it is cleared with Tara. As lab manager, I work closely with Tara to ensure things run as smoothly as possible; specifically managing scheduling, finances, and am a primary point person for student support. Please come to me if you have any questions or concerns and I’ll be happy to help or direct you to someone better suited!  
Contact: <madelinewoodley22@gmail.com>
