# Useful Contacts {#contacts .unnumbered}

A contact list for all lab members (including the Arcese lab), contacts within the university, and external project-related contacts can be found on the [shared Z drive](#sharednetworkdrive) and on the [shared Dropbox folder](#dropbox). There are many UBC employees that are equipped with knowledge that can make the transition from a new student to an informed student seamless.

Contacting the current CDLab manager with inquiries is always welcome and encouraged. Please do not hesitate to ask for guidance in regards to whom to contact with questions or concerns.

Natasha Thompson ([Natasha.thompson\@ubc.ca](mailto:Natasha.thompson@ubc.ca)) is the FCS receptionist -- is the go-to person for general admin related to the department.

Andrea Chan ([andrea.chan\@ubc.ca](mailto:andrea.chan@ubc.ca)) is an FCS administrator -- Salary, training, hiring paperwork, taxes, graduate research assistant hiring. 

Christine Mutia ([christine.mutia\@ubc.ca](mailto:christine.mutia@ubc.ca)) is our Finance Specialist for FSC -- out of pocket expenses. 

Rosemarie Cheng ([rosemarie.cheng\@ubc.ca](mailto:rosemarie.cheng@ubc.ca)) -- grant management Alice Miao ([alice.miao\@ubc.ca](mailto:alice.miao@ubc.ca)) -- Grant application, NSERC, application and processing of grants. 

Norm Hodges -- IT ([norman.hodges\@ubc.ca](mailto:norman.hodges@ubc.ca))