# Fieldwork Planning {-#fieldwork}

## Fieldwork Safety Plans {-#fsp}

Preparing for fieldwork is a very exciting time. When your preparation begins (as per discussions with Tara regarding your project) be sure to visit the following field work safety pages:

*	[Field Work Safety | Safety & Risk Services](https://srs.ubc.ca/health-safety/safety-programs/field-work-safety/)
*	[Conducting Off-Campus Fieldwork | UBC Research + Innovation](https://research.ubc.ca/covid-19/conducting-off-campus-fieldwork)
*	[Travel and Field Safety l UBC](https://travelfieldsafety.ubc.ca/about/)

A Fieldwork Safety Plan (FSP) is required for all fieldwork and must be submitted to your department for approval before you head out into the field. This approval process can take a few weeks hence it is best to begin thinking about the preparation of this document well in advance. You should receive an email from Pedro prompting you to complete this with the form attached, however you can also access the FSP document [here](https://www.dropbox.com/home/Conservation%20Decisions%20Lab/11_Health%20and%20Safety/01_Safety%20plans) in our lab Dropbox.

Before submitting your plan for approval be sure to glace at the ‘Field Work Safety Plan – Completion checklist’. You can find this checklist [here](https://www.dropbox.com/home/Conservation%20Decisions%20Lab/11_Health%20and%20Safety/01_Safety%20plans). 

Once Tara has signed off on your safety plan you are ready to submit your safety plan to Pedro Ribeiro (<pedro.ribeiro@ubc.ca>) for approval and archiving. 

## Research Ethics {-#ethics}

If you are planning to conduct research involving animals, including fieldwork, you will need to undergo the [CCAC Experimental Animal User Training Program](https://animalcare.ubc.ca/training) before applying for research ethics approval.

Similarly, if you will be conducting research involving humans, including surveys/questionnaires, interviews, or workshops, you will need to do the [TCPS 2 Course on Research Ethics tutorial](https://tcps2core.ca/welcome) before applying for research ethics approval. 

### RISe Portal {-#RISe}

[Research Information Systems (RISe)](https://www.rise.ubc.ca/) is an online portal that allows researchers and administrators to manage and track applications online through to approval, certification and awarding of funds. One of the main uses for RISe is ethics application and approval. Information on completing a UBC Behavioral Research Ethics Board application can be found [here](https://researchethics.ubc.ca/behavioural-research-ethics/ethical-considerations-research-design).

## Equipment {-#labequipment}

### General Field Equipment {-#fieldequipment}

The CDL field equipment inventory can be found [here](https://www.dropbox.com/home/Conservation%20Decisions%20Lab/01_Equipment?preview=Equipment+inventory.xlsx). This list is currently not up to date, so if you are wondering about what equipment is available please reach out to Aidan for the time being until the list is updated. If you require the use of any equipment please ensure that you alert Aidan prior to your fieldwork excursions to ensure that the equipment is up-to-date on repairs and servicing and is accessible to you (a great deal of our equipment is stored on Salt Spring Island).

If you require equipment not currently owned by the lab, please connect with Tara to discuss payment options. Depending on the equipment and lab finances, Tara may be willing to purchase equipment that could contribute to the overall function of the lab. Otherwise, this will need to come from the students' grant (*e.g.*, Mitacs research & material costs)

Please note that all lab equipment will be inspected before an after use; please use this equipment with care and as if it was your own.

### Lab Truck {-#labtruck}

The field truck is available for use by lab members for fieldwork (at a cost to cover gas/maintenance), please discuss with Tara if you think you may want to use it. It is a 2017 Toyota Tacoma 4x4 with a lockable canopy. The designated parking stall in the parking lot below Forestry is #15 (shared with Dr. Cole Burton's WildCo Lab) but the truck is often stored on Salt Spring Island and so arrangements to bring it to the mainland for work must be made in advance.

There is a UBC fuel card that should be used to fill up the vehicle, and is kept in a plastic sleeve in the glovebox. The purchase will then be charged to the designated project fund by Madeline.

When using the vehicle, please remember the following: 

- Fill with fuel at end of use (a use may be multiple days)  
- Use fuel card in glovebox to fill up and send photos of gas receipts to Madeline  
- Keep record of vehicle use (*i.e.*, trip details) and send this to Madeline

### Research Vessel {-#researchvessel}

The lab’s research vessel, *Seablush*, is a 6.26m outboard Silverstream with a 150 horsepower (HP) Yamaha engine and a 9.9 HP kicker engine. The vessel is moored on Salt Spring Island at a private marina in the Fulford Harbour. The vessel will only be operated by qualified operators, Dr. Tara Martin or Aidan Haigh. 

When budgeting the use of the research vessel for a project use the ratio of 1 nautical mile to 1.5$ of gas and maintenance. Marine engines should only be filled with mid-grade gasoline. Please take this information into consideration when budgeting for vessel use during project planning. 
