# Financial {-#financial}

## Student Budgeting {-#studentbudgeting}

### Proposal Development & Budgeting {-#budgetdevelopment}

Learning how to budget is an important part of your graduate student or research experience.  As you develop your research proposal for your MSc or PhD, create a budget for your project.  This budget should include all expected expenses associated with you graduate student project including field work, equipment, research assistants, honoraria, accommodation, field vehicles costs including mileage, attendance at conferences, publishing Open Access fees. Please try to be as comprehensive as possible.  Throughout your degree, it is your responsibility to keep this budget up to date and be proactive in seeking additional resources where needed. 

For vehicle and field boat use the mileage calculations are shown below. 
-	UBC mileage reimbursement rate: **$0.60/km for the first 5,000 kilometers** (the rate will be a little lower beyond 5,000 kilometers, closer to $0.58/km); Workday automatically calculates the up-to-date reimbursement rate when you are submitting your claim. This information is current as of January 2025.
-	Budgeting for use of research vessel: **$1.5 per nautical mile**

### Grant Management {-#grantmanagement}

Each of you are likely to have different streams of funding and it is your responsibility to keep track of your expenditure versus incoming funds.  
Please ensure, Tara and Madeline have documentation relating to your funding sources (admit funding package agreement, funding source agreements – e.g., Mitacs, NSERC) and that you keep track of expense receipts.

### Funding and Awards {-#fundingandawards}

Internal UBC & Faculty of Forestry Award Options can be found [here](https://forestry.ubc.ca/students/graduate-student-portal/financial-support/), described in great detail and with links. Below we have included a list of the awards, along with who is eligible, general dates, and overall value:

+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name                                                                                    | Degree                                                 | Dates                                 | Value                                                                                                                                                                                                                                                                   |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Four Year Doctoral Fellowship (4YF)                                                     | PhD                                                    | February 1 [incoming students]        | \$18,200 stipend plus full tuition coverage                                                                                                                                                                                                                             |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Faculty of Forestry Strategic Recruitment Fellowships (SRF)                             | Both                                                   | No Fixed Deadline [incoming students] | SRFs are available in amounts up to \$6,000 per year for 2 years (Masters) or 4 years (PhD).                                                                                                                                                                            |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Canada Graduate Scholarships-Doctoral (CGS D) Program                                   | PhD                                                    | Early September                       | \$40,000 per year for 3 years                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Vanier Canada Graduate Scholarships                                                     | PhD                                                    | Early September                       | \$50,000 per year for 3 years                                                                                                                                                                                                                                           |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Canada Graduate Scholarships-Masters (CGS M) Program                                    | Masters                                                | Early December                        | \$27,000 for one year                                                                                                                                                                                                                                                   |
|                                                                                         |                                                        |                                       |                                                                                                                                                                                                                                                                         |
| Affiliated Fellowships Masters Program                                                  |                                                        |                                       |                                                                                                                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Trudeau Foundation Doctoral Scholarships                                                | PhD                                                    | November 25                           | Up to \$50,000 stipend plus up to \$20,000 research and travel allowance per year for three years                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Mitacs Programs                                                                         | PhD, Masters                                           | Ongoing                               | PhD 3 years \$80,000 or 4 years \$106,666, or Masters 18 months \$40,000 or 24 months \$53,333 for research project award                                                                                                                                               |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Future Forests Fellowship                                                               | PhD                                                    | As posted                             | \$70,000 annually for up to four years                                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gordon and Nora Bailey Fellowship in Sustainable Forestry                               | PhD, Masters                                           | As posted                             | Fellowships totaling \$75,000, no less than \$20,000 and no greater than \$30,000 per student, the fellowships may be renewed for consecutive years to a total of two years of funding for Master’s students and a total of four years of funding for doctoral students |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Indigenous Graduate Fellowship & 5th Year Award, Grad Student Entrance                  | Both                                                   | February                              | \$18,200 per year for doctoral students for 4 years or a stipend of \$16,175 per year for Master’s students for 1 year                                                                                                                                                  |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| BPOC Graduate Excellence Award                                                          | Masters, PhD                                           | March 15, July 15, November 15        | \$3000                                                                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| China Scholarship Council Doctoral Scholarships                                         | PhD                                                    | March 2025                            | Approximately \$26,400 stipend plus tuition costs                                                                                                                                                                                                                       |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pacific Institute for Climate Solutions Graduate Fellowships                            | Both                                                   | Mid-January                           | Fellowships are valued at \$12,000 per year for Masters and \$18,000 per year for PhD students.                                                                                                                                                                         |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| International Development Research Centre (IDRC) Doctoral Research Awards               | PhD                                                    | April, October                        | Varied                                                                                                                                                                                                                                                                  |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| UBC Public Scholars Award                                                               | PhD                                                    | Early March                           | Up to \$10,000 twice, for a total of \$20,000 per student                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Forestry Graduate Program Internal Awards [**MANY**]                                    | All                                                    | Spring                                | Mix                                                                                                                                                                                                                                                                     |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| G+PS Spring Graduate Awards Competition [**MANY**]                                      | All                                                    | Spring                                | \$150-\$16,000                                                                                                                                                                                                                                                          |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| FRST Best TA Awards: Jordan L. Burke Memorial and Killam GTA                            | TA’s                                                   | Spring                                | \$1000+                                                                                                                                                                                                                                                                 |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Indigenous and Community Engagement Research Fund (ICERF)                               | Research Grant for working with Indigenous Communities | October 15, March 15                  | \<\$5000                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Indigenous Strategic Initiative Grant                                                   | Research Grant for working with Indigenous Communities | January                               | \<\$50,000                                                                                                                                                                                                                                                              |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Canada Graduate Scholarship Michael Smith Foreign Study Supplements (CGS-MSFSS) Program | Travel Grant for CGS/Vanier holders                    | Fall & Spring Each Year               | \<\$6000                                                                                                                                                                                                                                                                |
+-----------------------------------------------------------------------------------------+--------------------------------------------------------+---------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Here are some fantastic options for external awards (also make sure to continuously check the award section of Grad-Weekly emails):

+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Name                               | Dates                 | Value                | Link                                                                                                                                                                   |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| HCTF                               | T4W - April/May       | T4W - \$20,000       | [HCTF](https://hctf.ca/scholarship-program/)                                                                                                                           |
|                                    |                       |                      |                                                                                                                                                                        |
|                                    | Al Martin - April/May | Al Martin - \$10,000 |                                                                                                                                                                        |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nature Vancouver                   | April                 | \$1,000              | [Nature Vancouver](https://naturevancouver.ca/scholarships/#:~:text=Nature%20Vancouver%20awards%20annual%20scholarships,undergraduate%20and%20a%20graduate%20student.) |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| BCCF                               | March                 | \$1,000              | [BCCF](https://www.bccf.com/educational-scholarships/)                                                                                                                 |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| BC Nature                          | June                  | \$2,000 - 2,500      | [BC Nature](https://bcnature.org/scholarships/)                                                                                                                        |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nature Trust                       | Unknown               | Unknown              | [Nature Trust](https://www.naturetrust.bc.ca/about/scholarships-funds)                                                                                                 |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Freshwater Fisheries Society of BC | March                 | \$1,500              | [FFS BC](https://www.gofishbc.com/about-us/scholarships/)                                                                                                              |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Pacific Salmon Foundation          | August                | \$2,500              | [PSF](https://psf.ca/work/community/community-bursaries-program/)                                                                                                      |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Fraser Basin Council               | May                   | \$4,000              | [Fraser Basin](https://www.fraserbasin.bc.ca/Elizabeth_Henry_Scholarship_Fund.html)                                                                                    |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Nature Canada                      | Various               | Various              | [Nature Canada](https://naturecanada.ca/about/our-people/awards-scholarships/)                                                                                         |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Aerin Jacob                        | Various               | Various              | [List](http://www.aerinjacob.ca/funding--awards.html)                                                                                                                  |
+------------------------------------+-----------------------+----------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Expenses {-#expenses}

Throughout your time in the lab, it is likely you will need to submit a reimbursement claim at some point for a work expense you have personally incurred (e.g., travel, equipment, etc.) which should instead be paid for by a grant held by the lab. For students, in most cases this expense will come out of your own grant (e.g., a student might have a budget for “Material and Research Costs” within their Mitacs which can be used to pay for equipment costs). However, there may also be certain cases where the lab covers the expense.  If you anticipate this situation, please discuss with Tara before incurring the expense and then inform Madeline of the agreement you and Tara have reached (email Madeline, CC Tara, and include the cost or an approximation). 

For staff, all work related expenses are covered by the lab. These include: 

-	Work-related travel expenses (ferry, airfare, vehicle mileage) 
-	Meals when travelling out of town for meetings, workshops
-	Mileage to cover driving to field sites
-	Equipment and computing software – as agreed with Tara


### Small Scale Suppliers {-#smallscale}

If your project requires hiring and/or paying external contractors and you plan to file a reimbursement claim for this expense through UBC, please ensure that you contact Madeline about this as early as possible and most importantly before the contractor begins work. The process of setting up an external supplier or vendor takes about 6 weeks and requires paperwork involving all parties.

### Submitting a Reimbursement Claim {-#reimbursement}

1.	Email Madeline Woodley (<madelinewoodley22@gmail.com>) with the expense amount and expense type (brief description). You can either include this directly in your email or fill out the form on the next page (saved in the Lab’s Dropbox and Google Drive). Madeline will respond with the fund type (i.e., grant, gift, project, program) and worktag number to which you can charge your expense. If Madeline is unavailable, email Tara (<tara.martin@ubc.ca>) or Aidan Haigh (<aidanhaigh@gmail.com>). 
2.	Go to the Expenses Hub in Workday and select **“Create Expense Report”**.
3.	Use the following articles to help you fill out the expense report. If you cannot access the articles via the hyperlinks included below, go to the [Integrated Services Centre] (https://isc.ubc.ca/resources/workday-knowledge-base), follow the link to the [Workday Knowledge Base] (https://ubc.service-now.com/selfservice?id=kb_view2&kb_knowledge_base=af5ffe361b8ad4105edd43b4bd4bcb09) and sign in with CWL if prompted. Once in the Workday Knowledge Base, select "Workday Finance", and enter "Create Out of Pocket Expense Report", “Create an Expense Report for Mileage”, or “Create an Expense Report for Student” (depending on which article you require) using the search bar. Follow the link that shows up to take you to the relevant article.
-	[Create an Out of Pocket Expense Report] (https://ubc.service-now.com/selfservice?sys_kb_id=322e4bfe930392905a9f30edfaba1044&id=kb_article_view&sysparm_rank=1&sysparm_tsqueryId=57e9db6d93575650d557b2f17cba10cf)
  - For all out of pocket reimbursements claimed by staff, faculty or student employees. If you are claiming a reimbursement for work-related driving, see the next article.
-	[Create an Expense Report for Mileage] (https://ubc.service-now.com/selfservice?sys_kb_id=ae260e0a93cbd614d557b2f17cba1043&id=kb_article_view&sysparm_rank=1&sysparm_tsqueryId=37dadfa193975650d557b2f17cba1008)
  - Only use if claiming a reimbursement for work-related driving. Please confirm with Tara before submitting a mileage claim.
-	[Create an Expense Report for Student] (https://ubc.service-now.com/selfservice?sys_kb_id=4fbbd3b6938392905a9f30edfaba10cc&id=kb_article_view&sysparm_rank=4&sysparm_tsqueryId=a9fa5be193975650d557b2f17cba10a1)
  - This article is explicitly for out of pocket reimbursements for students (specifically those who don't have GRA or TA appointments). Email Madeline if you have questions and she will clarify with UBC Finance!
  - Staff, you should always use the first two articles!
4.	Once you have finished filling out your expense report, select **“Save for Later”** and then email Christine Mutia (<christine.mutia@ubc.ca>) with your EXP #. She will check over your reimbursement claim to make sure everything looks good and then either ask you to submit or submit it directly herself. Once you have had some practice submitting personal reimbursements, Christine will let you or Madeline know that can stop sending her the EXP #s and just submit claims directly yourself!

