# Financial {-#financial}

## Out of Pocket Reimbursements {-#reimbursements}

The two common types of reimbursements are travel and non-travel expenses. Copies of the reimbursement request forms can be obtained from Forest and Conservation Sciences Reception (rm 3041), and are also available in digital form for print on the shared drive and in the shared dropbox folder found [here](https://www.dropbox.com/home/Conservation%20Decisions%20Lab/07_Reimbursement%20forms).

To claim a reimbursement, you must have a copy of the original receipts and a speedchart (four-letter code) indicating which grant the claim will be charged to. You will need to send the completed forms and receipts to the CDLab manager who will review the information and will submit the reimbursement request to Christine Mutia. Each grant under Dr. Tara Martin’s name has a separate speed chart, please ensure that you have the correct speed chart information before submitting a request.

Please note that when charging kilometers driven please include a google map of the route that you took to prove the Kms stated on the expense form. 

## Small Scale Suppliers {-#smallscale}

When hiring or working with external contractors during projects please ensure that you contact the CDLab manager early and before the contractor begins work. The process of setting up an external supplier or vendor can take up to 6 weeks. Please speak to the CDLab manager for more information.