# Graduate Student School Survival Guide: Our Ten Top Tips {-#gradstudenttips}
1. Your health and wellbeing comes first! Make sure to establish a good work-life balance routine so you are caring for yourself, and your mental, physical, and emotional health. Eat well, exercise, go to sleep, stop drinking caffeine, check in with family & friends, and visit your doctors and/or therapists. Coffee ≠ Sleep
2. Learn to say no! Do not overcommit yourself and check in with your capacity levels often. Graduate school is a marathon not a sprint, and it is important to set regular work times and external deadlines to manage your time well so you do not burn out.
3. Don’t reinvent the wheel! Check out reference documents from other graduate students in the lab, including archived proposals, comprehensive slides, and dissertations for examples. We recommend timing your comprehensive exam as early as you can, closer to the finalization of your proposal, at the end of your first or second year. Check out the UBC graduate game plan for some student To Do’s throughout various steps of your graduate program.
4. Change up where you work! There are lots of fun places across campus if you want to change up your work space. Good library spots include the 3rd floor of the Law Library, Woodward Library, the Asian Studies Library, or any Library in the summer when undergraduates are gone. For coffee shops, the Beanery, Loafe, and Great Dane are fantastic locations. Also don’t wait in line for the Tim Hortons in Forestry–download the app or go elsewhere!
5. Take advantage of free & cheap experiences! There are a lot of free & discounted opportunities if you are a graduate student. On campus, the MoA, Beaty, Belkin, & Botanical Gardens are all free, and other places around Vancouver include discounted student pricing including the Vandusen Botanical Garden and most museums.
6. Go to cool Vancouver Festivals! There are really cool festivals occurring around Vancouver throughout the year you should take advantage of (aka work-life balance)! There is the Cherry Blossom Festival in the Spring, Bard on the Beach all summer long, Fringe Festival in early September, Vancouver International Film Festival in late September & early October, the Vancouver Writers Festival at the end of October, and the Christmas Markets in November and December.
7. Seek out workshops & seminars! Take advantage of free or cheap workshops & seminars for improving skill sets, often through Forestry, Beaty, and UBC Libraries. Subscribe to listservs for info on events (BRC is a good one) & actually read Forestry grad weekly every week! Remember you can Audit classes!
8. Take advantage of Free Week! Free Week—which is held at the beginning of each semester—provides students with the opportunity to try out the various fitness classes offered by UBC Recreation. These include dance, martial arts, yoga and pilates, spin, and other forms of group fitness classes (e.g., boot camps, cardio, strength, etc.). After Free Week, spin, yoga, pilates, boot camps, and other group fitness classes can be accessed on a drop-in basis through a Fitness Class membership ($95/semester for students). Dance and martial arts classes typically require registration on a semester basis. These more consistent classes can be a great way to not only build a routine but also meet new people.
9. Find healthy and cheap food options! On campus, there are some hidden gems for cheap, healthy food options, including two student and volunteer-run cafes known as Agora Café (found in the basement of 2357 Main Mall (H.R. Macmillan Building) and Sprouts Café (found in the basement of the Life Building).
10. Don’t be afraid to ask for help! Your fellow lab members are here to support you and have a lot of advice to give, so make sure to reach out! You never need to struggle on your own, and you are not a burden for asking for help! 

