# Field Work - How to prepare {-#fieldworkprep}

Preparing for field work is a very exciting time. When your preparation begins be sure to visit the following field work safety pages.

*	[Field Work Safety | Safety & Risk Services (ubc.ca)](https://srs.ubc.ca/health-safety/safety-programs/field-work-safety/)
*	[Conducting Off-campus Fieldwork | UBC Research + Innovation](https://research.ubc.ca/covid-19/conducting-off-campus-fieldwork)
*	[Travel and Field Safety l UBC](https://travelfieldsafety.ubc.ca/about/)

A Field Work Safety Plan is required for all field work and must be submitted to your Department for approval before you head out into the field. This approval process can take a few weeks hence it is best to begin thinking about the preparation of this document well in advance. 

A safety plan template can be found here in the CDLab shared dropbox folder [Safety Plans](https://www.dropbox.com/home/Conservation%20Decisions%20Lab/11_Health%20and%20Safety/01_Safety%20plans). 

Before submitting your plan for approval be sure to glace at the ‘Field Work Safety Plan – Completion checklist’. You can find this checklist in the same dropbox folder as stated above. 

Once Dr. Tara Martin has signed off on your safety plan you are ready to submit your safety plan for approval. Alter the CDLab manager when your plan is ready and they will indicate to whom you must send your safety form. 
