# Parenting Information {-#labmedia}

The CDL is dedicated to providing equal opportunities for parents. This includes accommodating parental demands, and inviting children and family members to participate in lab events wherever possible.  

## Parental Leave
Paid parental leave is largely dependent on research funders. 

Those funded by NSERC grants are invited to review parental leave policies [here](https://www.nserc-crsng.gc.ca/NSERC-CRSNG/policies-politiques/Wleave-Fconges_eng.asp). Depending on the grantee’s circumstances, the options include:

*extending the period for using the current grant funds by up to two years
*adding up to two years of funding at the same level as the current grant
*deferring the submission of a renewal application

To those who are funded by Mitacs, parental leave includes 8 weeks of leave paid at a rate of 90% of the employee’s salary (Employment Insurance and Mitacs top up combined equals 90% salary) as well as an additional 17 weeks paid at a rate of 40% of the employee’s salary. 






## 

